const DISEASE_LIST = [
	"47,XXY (Klinefelter Syndrome)",
	"Aarskog Syndrome",
	"Babesiosis",
	"Campomelic Syndrome",
	"Dandy Walker Malformation",
	"Eales Disease",
	"Fabry Disease",
	"Galactosemia",
	"Hailey-Hailey Disease",
	"Ichthyosis",
	"Jackson-Weiss Syndrome",
	"Kabuki Syndrome",
	"Laband Syndrome",
	"Machado-Joseph Disease",
	"N-Acetylglutamate Synthetase Deficiency",
	"Ocular Albinism",
	"Pachydermoperiostosis",
	"Q fever",
	"Rabies",
	"Sacrococcygeal Teratoma",
	"Takotsubo Cardiomyopathy",
	"Ulcerative Colitis",
	"VACTERL Association",
	"Waardenburg Syndrome",
	"X linked Lymphoproliferative Syndrome",
	"Yaws",
	"Zellweger Spectrum Disorders",
];

export default DISEASE_LIST;
